name: 'Next.js build stats'
description: 'Analyzes Next.js build output and comments on pull requests with page size and type for each route'
inputs:
  github-token:
    description: 'GitHub token to publish comments. Default: \$\{\{ github.token \}\}'
    required: true
    default: ${{ github.token }}
runs:
  using: 'node20'
  main: 'dist/main.js'
