name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install
      
      - name: Build
        run: bun run build
      
      - name: Configure Git
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Commit changes
        run: |
          git add ./dist
          git commit -m "chore: build [skip ci]" || echo "No changes to commit"
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: {{ github.ref_name }}
          force: true

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          artifacts: "LICENSE,action.yml,package.json,README.md,bun.lock,dist/*"
      
      - name: Get major and minor version
        id: get_version
        run: |
          echo "MAJOR_VERSION=$(echo ${{ steps.tag_version.outputs.new_tag }} | cut -d '.' -f 1)" >> $GITHUB_ENV
          echo "MINOR_VERSION=$(echo ${{ steps.tag_version.outputs.new_tag }} | cut -d '.' -f 2)" >> $GITHUB_ENV
      
      - name: Update major tag
        run: |
          git tag -f "v${{ env.MAJOR }}"
          git push origin "v${{ env.MAJOR }}" --force

      - name: Update major.minor tag
        run: |
          git tag -f "v${{ env.MAJOR }}.${{ env.MINOR }}"
          git push origin "v${{ env.MAJOR }}.${{ env.MINOR }}" --force
