on: [pull_request]

jobs:
  test_run_job:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    name: A test run
    steps:
      - name: Create build log file
        run: |
          echo "Creating build log file"
          echo "Creating an optimized production build ..." > build.log
          echo "✓ Compiled successfully" >> build.log
          echo "✓ Linting and checking validity of types" >> build.log
          echo "✓ Collecting page data" >> build.log
          echo "✓ Generating static pages (5/5)" >> build.log
          echo "✓ Collecting build traces" >> build.log
          echo "✓ Finalizing page optimization" >> build.log
          echo "" >> build.log
          echo "Route (app)                                 Size  First Load JS" >> build.log
          echo "┌ ○ /                                    5.57 kB         106 kB" >> build.log
          echo "└ ○ /_not-found                            977 B         101 kB" >> build.log
          echo "+ First Load JS shared by all             100 kB" >> build.log
          echo "  ├ chunks/4bd1b696-5b6c0ccbd3c0c9ab.js  53.2 kB" >> build.log
          echo "  ├ chunks/684-c131fa2291503b5d.js       45.3 kB" >> build.log
          echo "  └ other shared chunks (total)          1.89 kB" >> build.log
      - name: Hello world action step
        uses: aramikuto/next-build-stats@test-run
        with:
          build-log-file: 'build.log'
          dependency-install-time-in-ms: 1000
          build-time-in-ms: 2000
