on: [push]

jobs:
  test_run_job:
    runs-on: ubuntu-latest
    name: A test run
    steps:
      - name: Hello world action step
        uses: aramikuto/next-build-stats@test-run
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
